name: Dockerhub Image Push

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
              

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Build and push
      uses: docker/build-push-action@v4
      with:
        push: true
        tags: oluwatoseen/shola-app:v.1.0.2
